### ISSUE TITLE
Better handling of error response from disk resize request

### ISSUE THREAD

**Issue by dentarg** [84codes/go-api#23]
Just realised, `failed` isn't a string, the body of error responses look like this

```json
{
  "error": "Disk space can only be changed every 8 hour.",
  "error_code": 40002
}
``` 

So when running the provider the output was this

`Error: ResizeDisk failed, status: 400, message: map[error:Disk space can only be changed every 8 hour. error_code:%!s(float64=40002)]`

This is minor, we can update it later

_Originally posted by @dentarg in https://github.com/84codes/go-api/pull/22#discussion_r911815479_

**Comment by tbroden84** [comment]
Quick fix, not yet tested. https://github.com/84codes/go-api/commit/459487f71583aebc50c43aa15706904c77b093aa

**Comment by dentarg** [comment]
Nice, tested https://github.com/84codes/go-api/compare/disk-resize-error and seems to work fine 👍 So make a PR of that and we'll merge it and get it into the next release

**Comment by tbroden84** [comment]
Fixed with https://github.com/84codes/go-api/pull/26
